CREATE TABLE income_statement ( 
    id INTEGER PRIMARY KEY AUTOINCREMENT, 
    date_period DATE,  
    Total_Revenue BIGINT, 
    Operating_Revenue BIGINT, 
    Excise_Taxes BIGINT, 
    Cost_Of_Revenue BIGINT, 
    Gross_Profit, BIGINT, 
    Operating_Expense BIGINT, 
    Operation_And_Maintenance BIGINT, 
    Selling_General_And_Administration BIGINT, 
    General_And_Administrative_Expense, BIGINT, 
    Other_G_And_A BIGINT, 
    Selling_And_MarketingExpense BIGINT, 
    Depreciation_Amortization_Depletion_Income_Statement BIGINT, 
    Depreciation_And_Amortization_In_Income_Statement BIGINT, 
    Amortization BIGINT, 
    Other_Taxes BIGINT, 
    Other_Operating_Expenses, BIGINT, 
    Operating_Income BIGINT, 
    Net_Non_Operating_Interest_Income_Expense BIGINT, 
    Interest_Income_Non_Operating, BIGINT, 
    Interest_Expense_Non_Operating BIGINT, 
    Total_Other_Finance_Cost BIGINT, 
    Other_Income_Expense BIGINT, 
    Earnings_From_Equity_Interest BIGINT, 
    Securities_Amortization BIGINT, 
    Special_Income_Charges BIGINT, 
    Impairment_Of_Capital_Assets BIGINT, 
    Write_Off BIGINT, 
    Other_Special_

)